# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e963b38183322da5bf96699526a1702c3c4548dbb1a3fc18017d2d6dd4e704cb91ce58b31ca109a237039176652fac0eb7e25e730badf2003d5962d292e9af7
  client_secret: $ec0ndl3ad

test:
  secret_key_base: e9a7c0a2798f271a25e1fe8a8e2373f6fe978958680784734c839061281b9cfa98b412fbec4bda48aff45a5218997a415a93ea4d3a6650005f7627bfe26e014e
  client_secret: $ec0ndl3ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  client_secret: <%= ENV["CLIENT_SECRET"] %>
